MIHOMO_WEB_UI_PASSWD: ENC[AES256_GCM,data:1iVG/litF+txa2qGtA==,iv:OeW+Lb1UJ9FwI7fX0SJNRzCe4SPZl5kkaC1P28ITgB8=,tag:/Q3CKYGXEdJQ7Jv9cJhKtw==,type:str]
sops:
    age:
        - recipient: age1xdlmmj7gvvmvpl7n28yv6l9zsrrlazyunesyrzhzy37n59zexepsp4gpxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6L1dnTzRySlhkVHhscEVk
            RmpuMFhxV25lOGIyaFhOOUNPU0twNmZHV3c4CkF0MXBXSWhGTGw3cGFsK2NEc2g3
            emk3alNLY3BJMElteXJEcnQxeGNhUDAKLS0tIE50Z0o0c0VyUDl6ZUE0NHdodE4x
            ZCtGL3FaUWIvRjdDeGxJbjZ6ZFR5eGcKWad7Vk9h+5mCSfwes1Ys3Ai6EU1xfGgX
            7R1ThzNTe7fLvlN1AjMFA3GBdsXN77AznJIfrK6hsg87CQim4RgUBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T06:42:58Z"
    mac: ENC[AES256_GCM,data:fVUO72InarN+7Bxaw2eQFTdyBkvns39EOlr1n6NSRVVO+v0bHhZJZPzQJku+4xATdMw1fobmXWg27MVXaFo/Dc2YaPETuHqHESmOya7uK2jg6u6fQH6VZ90a2dJz5l5ntoZ5r/T+NqHOvzDvPJ++zNoXy/3el0b3M8cOfZ4E+N8=,iv:u8BJiMe3L7gUxE/xyGLfQf9D79p0Ievte1UWPMiKx/A=,tag:1wYcFZB+kn5pmPlz3ZNw4w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
