# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6c04c5ca-a28b-4138-acdb-247dfe55a701";
    fsType = "ext4";
    options = [
      "noatime" # 必选：不更新访问时间，大幅减少写操作
      "nodiratime" # 可选：noatime 通常已包含此功能，但加上无害
      "commit=60" # 激进优化：每 60 秒才刷盘一次（默认 5 秒），大幅减少唤醒和写入
      # "discard"        # <--- 删除此项！(下面解释原因)
    ];
  };

  # 2. 引导分区 (VFAT)
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CA10-C928";
    fsType = "vfat";
    options = [
      "fmask=0077" # 优化：仅 Root 可读写文件 (原 0022)
      "dmask=0077" # 优化：仅 Root 可访问目录 (原 0022)
      "noatime" # 优化：禁止更新访问时间
      "errors=remount-ro" # 优化：出错时挂载为只读，防止损坏扩大
    ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
