{
  lib,
  basic-config,
  dns-config,
  proxies ? [ ],
  rules ? [ ],
  proxy-groups ? [ ],
  proxy-providers ? [ ], # List<Map<ProviderName, ProviderAttrs>>
  rule-providers ? [ ], # List<Map<ProviderName, ProviderAttrs>>
}:
let
  concat = builtins.concatStringsSep "";
  toYAML = lib.generators.toYAML { };
in
concat [
  ''
    # mihomo config file, generated by mkMihomo.nix
    # Do not edit this file directly.
  ''
  ''
    ${basic-config}
  ''
  ''
    ${dns-config}
  ''
  (
    let
      yamls = builtins.attrValues (
        builtins.mapAttrs (provider: content: "  ${provider}: ${toYAML content}\n") proxy-providers
      );
    in
    ''
      proxy-providers:
      ${concat yamls}
    ''
  )
  (
    let
      yamls = builtins.attrValues (
        builtins.mapAttrs (provider: content: "  ${provider}: ${toYAML content}\n") rule-providers
      );
    in
    ''
      rule-providers:
      ${concat yamls}
    ''
  )
  (
    let
      yamls = builtins.map (proxy: "  - ${toYAML proxy}\n") proxies;
    in
    ''
      proxies:
      ${concat yamls}
    ''
  )

  (
    let
      yamls = builtins.map (group: "  - ${toYAML group}\n") proxy-groups;
    in
    ''
      proxy-groups:
      ${concat yamls}
    ''
  )
  (
    let
      yamls = builtins.map (rule: "  - ${toYAML rule}\n") rules;
    in
    ''
      rules:
      ${concat yamls}
    ''
  )
]
