MIHOMO_WEB_UI_PASSWD: ENC[AES256_GCM,data:tH+Wn4syjQH+Ms6UcA==,iv:HRjnqYkx7I5BEKup0txREXWjCnffYrqVQhkCjMegbgk=,tag:XYY1s7aczQYUN1TI8brzdw==,type:str]
sops:
    age:
        - recipient: age1uyr2r6hjsntpd38pnqzt496m2te55ujue2xzh25q8hhpfl33442qsn4h58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTmY0RlhXR0lodDh1MmJD
            bExFbGxyK0xheGo3aDFnaU84SHRReU45aTNvCmhCa2lPMUFoTUg5dTkrRmMva1BY
            aVRqRGFPTUhNSlFDNC8ra0hvTWZSazAKLS0tIHVyNmxPdXpOWDJnMDgxaGVJV1l6
            RXZKVkl1K0hoYzlkb1ptR250enBNOEUKz6KwDO1a/mDDF1ZFtcqwTHXaQbWE1K0b
            yNMHXbanVmiuFGeKbUNTxQdN02f4FyyYLYO4ZUVAd9z+3wXtLpKwkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T08:13:07Z"
    mac: ENC[AES256_GCM,data:PDLFAeBXlNuYi52MSS2YngG7YG9N7oNpSretrgtFE+CInsnwP26NLpikekSrEEgA4IMmR6NllvorOIwg/iDpXa+uEsJJ9ExvIJuXAIuw4J4lMcLe3qir+nrQdWA1xNZB1rvnGp0NIL/K3tn1d6x8Wmmc7uhlVopLFUE0zQbXROU=,iv:dNU2+0NyqEvSOLpznoHil3mpOhPRUW977z96SbQUoBQ=,tag:/APvTm0QvnPidIOJXT9KQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
