MIHOMO_WEB_UI_PASSWD: ENC[AES256_GCM,data:UtsTTvvxsSh3Y2S2ZQ==,iv:R3nScn2NRWmAAdbMDCG02GEm+SYAKWmaVJWotfE5S9o=,tag:Letxhuhjspe6VW49wMEQww==,type:str]
sops:
    age:
        - recipient: age1jlsr9ff6adssdjqdtqxuwr0vxszj9sz4pmg47gygktjfes47lsfq7ff4zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYnluWTFuT2hBNitoOVFa
            SUg3TExWeW1YZTQzSGtzNlQxTWI3NmR4NkNjCjZSL2dpMUR4VnI0ckUwejZYbWc1
            aDlxS043aHh6cDlQb0lYbEFHSGpISmMKLS0tIEkxR2Q0eEFpdGNtekFyYXovV3My
            UHdHSWJ3TkZrMlNkSE9IcU9maUxuRTAKr9i6dmICW2RPADCVLNbZFAsoZA3PuMKJ
            s2W69SHQblIT2hb5ysaHKHS0v4XfM2pzGDMtrEeSGseFwnwYpM2m7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T14:28:53Z"
    mac: ENC[AES256_GCM,data:4rAWqu8UMazCyL0S/veCnOrC5o1USJ6nbdAze1PD2sMjwlUuFJ1mSCb6TJFwtj92yMSWsLFjuDb5WwExcIOg4IRGhkrNpSGu9lc25iW2jFPBLhCPbQorxMQuoMYCxGLK1qOaZwjfGKnQXVz9yXtwcOkeo7mDw9QD5Waifa5y5go=,iv:ILTDZK8o8dXNHX5lXvwIIiB1kGVLao63vzuSV4V2Ueo=,tag:r8rAYYioRRMq5/mmwTL8lg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
