MIHOMO_WEB_UI_PASSWD: ENC[AES256_GCM,data:KyW1Np7EPYRivn7K,iv:x7X8c8RbsYMRkOYBmR7UhPw8xEMmyH34Y/evKv6c4o8=,tag:IWNvm3NwQhFuCKabZ800rg==,type:str]
sops:
    age:
        - recipient: age1jycrhjpfpw2n9rszq6056zqt3552pr38d3vz2mk8udetglrk0pfqhfhtnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SFRNUG1DZjZDMmswUVZv
            UnVxZGRiOE9CNlE1ODVsMVBrbEx5V2QrNXlZCmEvUnhkSXB1VFhGZ2EwNHEyT1o5
            bVY0Z2FUSi95cDUvOHo4M1dUTU4xTmMKLS0tIEtJNGJtM1Z2ODFidnFGRU5qVnJC
            N2d0UHZjdUloUkc3bERuYU1kOEMwUmcK7XDuMZ8vUjCvW09NW7ov/Uc/ZhE6jm4Y
            1PkdKsLRoGBfxT2HAITAX6s74SuUuB8SDW8o7zX/dgpyvNW2MPCbvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T14:00:23Z"
    mac: ENC[AES256_GCM,data:0m9AHwSLtsJdI6YQZc/2CFrTh6z7SLa1/FGXsMUMqllDmDdluxCRP/NqdzkqDu9AdqG5/+9KMsOajmtXCfya2+aLQCINWqXPxb8cnUfSDa17Uqwv1kTPxMw3eY4Qk9beB+R6tupzNygCMfB+zpIVu6Blhov2Bw9/mdLhVeJkvwA=,iv:L1nYpxgJQI0oWwW5kP37OBTnyEZ1UpFlekjVjaRzSg4=,tag:cnjkJl+Tl8fgv1wNVsdaDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
