{
  lib,
  basic-config,
  proxies ? [ ],
  rules ? [ ],
  proxy-groups ? [ ],
  proxy-providers ? [ ], # List<Map<ProviderName, ProviderAttrs>>
  rule-providers ? [ ], # List<Map<ProviderName, ProviderAttrs>>
}:
let
  concat = builtins.concatStringsSep "";
  toYAML = lib.generators.toYAML { };
in
concat [
  ''
    # mihomo config file, generated by mkMihomo.nix
    # Do not edit this file directly.
    # refernces: 
    #  - https://wiki.metacubex.one/handbook/
    #  - https://clash.wiki/
    #  - https://linux.do/t/topic/163682
    #  - https://linux.do/t/topic/832271
    #  - https://wiki.metacubex.one/example/conf/?h=geodata#__tabbed_1_3
    #  - https://clash-meta.gitbook.io/clash.meta-wiki-older
  ''
  ''
    ${basic-config}
  ''
  (
    let
      yamls = builtins.attrValues (
        builtins.mapAttrs (provider: content: "  ${provider}: ${toYAML content}\n") proxy-providers
      );
    in
    ''
      ###########################################################
      # proxy-providers 代理提供方                              #
      # ref: https://wiki.metacubex.one/config/proxy-providers/ #
      ###########################################################
      proxy-providers:
      ${concat yamls}
    ''
  )
  (
    let
      yamls = builtins.attrValues (
        builtins.mapAttrs (provider: content: "  ${provider}: ${toYAML content}\n") rule-providers
      );
    in
    ''
      #########################################################
      # rule-providers 规则提供方                             #
      # ref: https://wiki.metacubex.one/config/rule-providers #
      #########################################################
      rule-providers:
      ${concat yamls}
    ''
  )
  (
    let
      yamls = builtins.map (proxy: "  - ${toYAML proxy}\n") proxies;
    in
    ''
      ###################################################
      # proxies 配置代理节点                            #
      # ref: https://wiki.metacubex.one/config/proxies/ #
      ###################################################
      proxies:
      ${concat yamls}
    ''
  )

  (
    let
      yamls = builtins.map (group: "  - ${toYAML group}\n") proxy-groups;
    in
    ''
      ########################################################
      # proxy-groups 配置代理组                              #
      # ref: https://wiki.metacubex.one/config/proxy-groups/ #
      ########################################################
      proxy-groups:
      ${concat yamls}
    ''
  )
  (
    let
      yamls = builtins.map (rule: "  - ${toYAML rule}\n") rules;
    in
    ''
      ################################################
      # rule 配置规则                                #
      # ref: https://wiki.metacubex.one/config/rules #
      ################################################
      rules:
      ${concat yamls}
    ''
  )
]
