hello: ENC[AES256_GCM,data:gxsAjAjBK32cH+65k65lzGxdCZuqGTWgW8KTIRAVEOodU1MoYlI1ubAtE/Av,iv:alisjQNsVFpqV2x+8jEHuhPtJO7HSRaJwMkcB54DH6s=,tag:b34GrLthuEHFVJYwJKhmQg==,type:str]
example_key: ENC[AES256_GCM,data:w6HKDHfBuh9xV1r6qg==,iv:YJ5IDcPclkzMpFElRZr9xhCO9M6YsX4rBCv6ga7CwPw=,tag:u5QdShkQIB1v2KuNDbAIMA==,type:str]
#ENC[AES256_GCM,data:ZG/Y1X/qKGamYb1Ei9gK6Q==,iv:y5dh1QmU3RAfWrmArhhw2zxHZ6Smnq1ADfv8GlJM/3w=,tag:LtshHMzctyNIaWjmTRd1NA==,type:comment]
example_array:
    - ENC[AES256_GCM,data:77nhbqtrdtmutXGF2M4=,iv:ksjrGWaU0/iK8q1Eb75O0IqF74fOHcE3M0iGyzc90Sw=,tag:EuoAKK+t2RJuXBtGvVedbQ==,type:str]
    - ENC[AES256_GCM,data:eygOZcrWz7N2cOLvLhk=,iv:3wnl9Y2SKVm21D8YoC6zDrw8+bpNdmingaEurOK9xEQ=,tag:YQgzCwejUjdxgp2MOkMGRw==,type:str]
example_number: ENC[AES256_GCM,data:Nuou63fYRkMnEw==,iv:pDVj56e2cu5Lpm6/jyC9E11SjEzyNut3f0uJMYJjS20=,tag:UEtyAVxHlBcJMn/hifNWeg==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:mPNV/Q==,iv:QtmqDV8yYl71HvnouMZ/cSrjg4e3rW1YPZ3e5SoA7N4=,tag:Ruw4tZkq8vDyAbSKo6Mzcw==,type:bool]
    - ENC[AES256_GCM,data:USgDCys=,iv:xXi8werRtG3+BkPiVY3Tz2h4uQecMbYMf8uDPR1ZRXI=,tag:LjXQdj1DsBd8qMz0iiX9AQ==,type:bool]
sops:
    age:
        - recipient: age1jycrhjpfpw2n9rszq6056zqt3552pr38d3vz2mk8udetglrk0pfqhfhtnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYnNIUFpDd1BRQTQ2T2xk
            UW1XeEIwekFtL0Vzd0tlZVhWZWRsK0VMSEFrClZhZVBmYjRtaFAzNjM1c2ZSRnJW
            dHhERi9IUTlxeDhTR21LMEt1K0dia2sKLS0tIG1BNVZ0VVh2VlI0YjB2b05yblNZ
            bnFvZUpCWEFRcGJ2ZGEvZjI2bjJ5UXcKWeId7Xj33ydWLfTnBd0T49ue0/OOWM2v
            8SJGb2vv50EXbC7GPMNeXtDAZHOuP5fJYFx52z5jVmMGDbWYh9wZdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xdlmmj7gvvmvpl7n28yv6l9zsrrlazyunesyrzhzy37n59zexepsp4gpxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aDZlbnNFZTlnUjJ1d1lR
            VzRlMGRyRVlwUzdJSHlPMzg4QzlnY0doRGtVCnV5cmNsUXIrd2dQWDZQS3BZRFNs
            WXd3c0RZTzAyd3p5VmdzRWpZUGQ3UTAKLS0tIEQ5ZUpkU1NNVjhoNjlVYityaEhj
            MVdITzJNY3Uyb1g0MlQ1RUJ1eHlONlUKpWEmzTw+YG/Psk3JLzodwQUnQtPqCUmL
            Mbo7sg4pRwuvjSQ0+YwdrxTS1mBoRcLpR+gG19DW8P4w0itquw+/yQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18gjva8lxepd4gc5whz73q39xjerphtm6nmfaax9ye9f2dzsj293qgg7xw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWajA3WlJiQmJCMVdSalIz
            OG12L0NjNk44dUlUYmdGMHA3czFWRWI4STJ3CnFVSExVWnZBbGgraFNFdGdWcjA3
            WlN1VWdPNTVTaDJKTkdKcVRpd044NzQKLS0tIGxuRjFxWThOOTJtTUZQNW1CMS9Y
            OTJDWmVGVTAzNjB5Z1VWaStVaXBlTUUKBJoAr7uIivEgtR1CE561SXmvvURzCs7Y
            hpkRaBwGPeBOBj847vuEFz8I1Z4yBvXGA0s3ZXuIt2f+jWXI3puHRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l87qwdwrfne2mrln99qnek0yl72xecg5lrgkqps9cpz7z356kf2s4hsplc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOGhqbGhUcWRqRUlaWnpm
            U1lBdDVOcnlKUkk5cjE5QXlsVkQrZVRyVEJnClJ3b3pwV3pKTlpiWGVQK01kSTJo
            SnlmcVpJMHl4VjNLTTdpeE9FYnJkZHcKLS0tIHg5dFJkaGZVaWloRDYwQlBCNVll
            M0NjaXhtWnFDUkJ3cWJrOUlRLy9RU28KlftFKR1++/Wj3su2Uzsz9I86oLncUr1v
            YPmhBgM/FMTBCclAZT0TyAFUveH05kXN9rAFeZKJOlT6tRtiLX8pQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18cwlfuth4jpz03u9wzwq5rxxxx50w9e0me9sjqt29dtra0xh33ss7xtfs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS1pwM2ZLUktkSkl4djBR
            WElQODV2eVNSZmF2OEYwNW02ZlBWWFB6Mlc0ClhhU2ZWdUxic2daZTIzYVJEQXZC
            ZTVTMVBCL2ExUmFrcUNCODhBKytTVEkKLS0tIDdUSVBhVis4UHdvRUpDVVFycmww
            NFVKZnAzdHA0ZUhEc0VETHZvUkIvNmMKmk77SAjwvPUwpIT5Ab5kLc4mLv0r42Db
            /YVaKh2ALH31IVxs02k2W3xka44+cc5i9wc9jBYBc4pyq3ZDw0dvcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1se6rw68dnwf6896j8r2v2vjf3kvm5l2x2220epdnm4k2xwzjee7qqj9hl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQzVaUzNCcWpUZWFmb1I0
            Z1JnZ0l5TkpHZnJBRkFKL1dyQ1F1dFJOZG1jClpNbkJxRnFuM1N0YzlLSzVDaFhM
            R1JMT01KS3IrYWNmaDFXNVpYL3Q1UncKLS0tIGY0OTVyczRZUS9qZ1o1bm9kY0FU
            VUFaQ3BZWDU1ZkR3RE9CNXNhazRMUUUKZV9XJMr7awv4AL3K0mGB7Ar2zMFllTU7
            YuwE84S5byTniJSPcJInBDbDNehmtp14nlr6yRKElF659091lAJ0yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T23:20:40Z"
    mac: ENC[AES256_GCM,data:E7E+hQnN5eeKOs4faElgkeMukSbyJTwDYcf3+xDLh2WC9adq6oCaj7I5siydEZ0JzIZvdMN3ygxTUqt3Cg4vYDN5XHuxHWagcEjZ9+U+W6JhutUmPcSxGWVGjtPDTWCD+xJazNuT40yvLEOK2XxA+zwPIaN/2pjARbrFa0k+Olk=,iv:CdhbcJsdPGF8UH3qOTEnkXl8l8mkl6yMqyIoYrVYoUc=,tag:WwtyCzstqBUGJaeYuc3+MA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
