hello: ENC[AES256_GCM,data:gxsAjAjBK32cH+65k65lzGxdCZuqGTWgW8KTIRAVEOodU1MoYlI1ubAtE/Av,iv:alisjQNsVFpqV2x+8jEHuhPtJO7HSRaJwMkcB54DH6s=,tag:b34GrLthuEHFVJYwJKhmQg==,type:str]
example_key: ENC[AES256_GCM,data:w6HKDHfBuh9xV1r6qg==,iv:YJ5IDcPclkzMpFElRZr9xhCO9M6YsX4rBCv6ga7CwPw=,tag:u5QdShkQIB1v2KuNDbAIMA==,type:str]
#ENC[AES256_GCM,data:ZG/Y1X/qKGamYb1Ei9gK6Q==,iv:y5dh1QmU3RAfWrmArhhw2zxHZ6Smnq1ADfv8GlJM/3w=,tag:LtshHMzctyNIaWjmTRd1NA==,type:comment]
example_array:
    - ENC[AES256_GCM,data:77nhbqtrdtmutXGF2M4=,iv:ksjrGWaU0/iK8q1Eb75O0IqF74fOHcE3M0iGyzc90Sw=,tag:EuoAKK+t2RJuXBtGvVedbQ==,type:str]
    - ENC[AES256_GCM,data:eygOZcrWz7N2cOLvLhk=,iv:3wnl9Y2SKVm21D8YoC6zDrw8+bpNdmingaEurOK9xEQ=,tag:YQgzCwejUjdxgp2MOkMGRw==,type:str]
example_number: ENC[AES256_GCM,data:Nuou63fYRkMnEw==,iv:pDVj56e2cu5Lpm6/jyC9E11SjEzyNut3f0uJMYJjS20=,tag:UEtyAVxHlBcJMn/hifNWeg==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:mPNV/Q==,iv:QtmqDV8yYl71HvnouMZ/cSrjg4e3rW1YPZ3e5SoA7N4=,tag:Ruw4tZkq8vDyAbSKo6Mzcw==,type:bool]
    - ENC[AES256_GCM,data:USgDCys=,iv:xXi8werRtG3+BkPiVY3Tz2h4uQecMbYMf8uDPR1ZRXI=,tag:LjXQdj1DsBd8qMz0iiX9AQ==,type:bool]
sops:
    age:
        - recipient: age1jycrhjpfpw2n9rszq6056zqt3552pr38d3vz2mk8udetglrk0pfqhfhtnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOG9zSjN3cEwyREpWczlr
            NGtlRURBemd6cTU5a2R2cE1valRTWDhqSGpzCjk3VlZqejVBL0ZSNUNxbDF1NHd4
            cHJxY2V4ZHlHZzZGVDNuTHVqOWdwTFUKLS0tIHhTSFdFODZtWFA2ZS9IcjdQNENw
            ZzIySG4wT1VWYmFWL1RnbUZ2K1ZnNXcKIXdAKGD7l+V83A6OAoMMJigyJBs8Hleb
            RyTShF9Rh/d8znypkBhMAv772PlawPOfKtJUAhhWlzxIJMdF+d7G5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xdlmmj7gvvmvpl7n28yv6l9zsrrlazyunesyrzhzy37n59zexepsp4gpxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQS2VWSGJSU1RBTDJtQi9H
            TWpKUVoxcGRHa1lvSTk2cFZGcjh3SzIwTzBzCnk2cHEyd0duZ0Zqa2dFWTdBdGRC
            TDdqT003ZTlKSDRQU0hueDIydEpmU2cKLS0tIHZ2aS9USmw5UTlScVgycjRPYVpa
            TlhOL3BxK205blZsb2RCaVVwKzlicHcK+nTtxp7/8PR3UV60KfCnUx6V0TsKCWd4
            KWKrxD9/akWYFNm6LgOmYaLjK0H6zxImFTieJXij9sjWI/d5fk8lZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l87qwdwrfne2mrln99qnek0yl72xecg5lrgkqps9cpz7z356kf2s4hsplc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TW9na0Rnc3o3VS9TenBU
            aHkxc1hqQ3VlajVOT3ZuL25Za3Rpc29ZeFYwCk8waGpkdjBoeUdBSW1mRit1bERi
            NklDMHdGb293b1ZIKzdtc3ZGeHBRR3MKLS0tIHpPcGpqMGpXSlk4aDZISXFqdFBu
            dDMranlCQi9BVEUwWjBKZGhWS1JWRGcKL/2FbbUwRPeKvdZSi7eTGq3ELn3/OLOW
            bTOdHaFlBAHRMd3/huE+o8D1EgIp13TF7mltDTMBLSFrLy/em5ShIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18cwlfuth4jpz03u9wzwq5rxxxx50w9e0me9sjqt29dtra0xh33ss7xtfs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdVRXVXV0c3kzYUR3MTdV
            M1lGVVNxMTJUTGQyZ29tTkE3Nmk2RTJsZmhVCklXcFQ1K29qOE92ZU0vUEQxd1dF
            aWpWcVh1dG84RVExQlZQN094TU95U3cKLS0tIFlEdk4yeEoyeGFkV05lOVhYZEh5
            a0taNVkxTlFkazcwYmxuSlZzbVpUMzgKDlgd5ZaqqUHkYBNeXgzdyj43kdi17V6f
            7ZS+RcKviiT6DDsfw5XxEIZc4xkQ+W8XxBd4opn0FfNDc+e21RqiAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ymn47ncldl8eex7a6hq2drh5y9qhh54e9f2dxdjz8a9e83x2aatsmuw45p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeE9xQXFDYVJMY3VPUTND
            RXRQVmJObzFjS1YzNmpkVDdyMzI3Rm9mVnhFCmVqYlhwaVpNSnI4UHRITDBlckhz
            MG13ODJScE9qV2JNNi81akNMcGgzUEUKLS0tIGpiZDlDNlVZbFhkOTY5V0Nra1Zj
            RkFiRUNtSmNqb3FoZGRqK25Kb1hiL0EKaBBPvWyGHDoDDrMf1BfAUkFuAlZ5CyB5
            OzzhWM6lUJZpvc9+Pt8szBrPaxam5gHkzGL6TrdR/eHPxNPcGrRa9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T23:20:40Z"
    mac: ENC[AES256_GCM,data:E7E+hQnN5eeKOs4faElgkeMukSbyJTwDYcf3+xDLh2WC9adq6oCaj7I5siydEZ0JzIZvdMN3ygxTUqt3Cg4vYDN5XHuxHWagcEjZ9+U+W6JhutUmPcSxGWVGjtPDTWCD+xJazNuT40yvLEOK2XxA+zwPIaN/2pjARbrFa0k+Olk=,iv:CdhbcJsdPGF8UH3qOTEnkXl8l8mkl6yMqyIoYrVYoUc=,tag:WwtyCzstqBUGJaeYuc3+MA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
