#ENC[AES256_GCM,data:C1PQJKQYzW00Kg==,iv:2JEpEAH35byfR28+Qj5uP9l/kjGYb+jjKS1/lp9fRAM=,tag:f2LhYj2XBlBhmKNrmmCPVQ==,type:comment]
MIHOMO_IKUUU: ENC[AES256_GCM,data:jxQ6K6E7kPqzCx/6mVYj5IKk8vFF2JKwCsGemknCGVBkQrfMGTQ8lYSu51pgyo802Yh4BcYEP/QKuoz1ZGxHEduE+vYirg==,iv:89wXEu3YMBXOVa3oXZgy6jqeaHxboKnndyADCJfvy1s=,tag:bGdPoyasn4VjEmCIoOcatg==,type:str]
#ENC[AES256_GCM,data:EpL7vfBmxz9jL4JjoOmjzV0=,iv:nrLMGIAAkno88/G2s0KMaw0dypF3ZmLHMCJjBPBsNvk=,tag:a8gbJ06wjERnR0fEmFSWBQ==,type:comment]
MIHOMO_LEITING: ENC[AES256_GCM,data:nYCVV+3jwLFzDRi0kaS4g8swsECiWqrSAQnFJlE8ZDm8tWM4K3R/rrhcZAi/GMetQjJzImG5rBdQIDMqlz5GoYkYqJnjKydD7CncjNIyTA==,iv:w1OclwnovB+k59fQGeYw1rRUDySf1Lf3ly39bsNetxA=,tag:WJORccccFUlH++RSU2pYog==,type:str]
#ENC[AES256_GCM,data:/KMqL+fYyEyKBA==,iv:X2yrCZoYES08bLKj0IxUqIPy/g3lKDRiC6qtW/URQ00=,tag:oT0g28PYFo4+NAFXrAudxA==,type:comment]
MIHOMO_MOJIE: ENC[AES256_GCM,data:Jz8GaPJ2g1CvGyQ+rSCB2WFnjnzQXjVYkPi3gHz5zK/nYrO4EaIRv8x12kT0qWgcICtIC7InNebMeUzYsYZPVpS9inLDN4hNxYmyGQEF2DVIKyYNzPg=,iv:91iAOE9gtlzWyWFth4amffQ/y8thm2a6Z7prNdSA6k8=,tag:T98u4xSPSu0LhpXhab/7UA==,type:str]
#ENC[AES256_GCM,data:mOsOCYMmtR5AD/iCVj+nyrtSk/WV+I9PyA==,iv:dfHT7Um0aOZMDYUKW2Hq7wxNRVw3pp3yKdPU02PG9HI=,tag:SBRpbZfPC69kcv5+2giqDA==,type:comment]
MIHOMO_SECRET: ENC[AES256_GCM,data:iP9U1zPknXv0pLGa,iv:Uj24VHiX4HhpR09/ukX7rzpTnSQmZ5y9IKrD4TbISaQ=,tag:yXODr+4sbgzRn3lsgnqtAQ==,type:str]
#ENC[AES256_GCM,data:TR7lB3K2ZJ4/YYe7C0zGaflX168=,iv:cG4jwVmK94eyect5k2rBONMfgaZ6RBWFAajoQ1FeVkM=,tag:ZwU1gb2KLYoBA/O2Q5vXZA==,type:comment]
GITHUB_ACCESS_TOKEN: ENC[AES256_GCM,data:51V3TL0jiDHxJ2FAEIZ1edYZqGKFZ4HnQ829XH9mBZphOKp1KsT9b0QSQLFvA+gPpQNPFZp4dAWYXjuom9/QZz3QemsHHUR3BfchF88xpykefJ3SwRANhnZgbDYB,iv:hT9a9riVJggDTY55SnuRndWhW+OOQs2QK9zNKzF5CYI=,tag:HWcoYoTf3cHIA14hoz4aJQ==,type:str]
sops:
    age:
        - recipient: age1jycrhjpfpw2n9rszq6056zqt3552pr38d3vz2mk8udetglrk0pfqhfhtnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid0d6UDV1c2w2ZFEyeWhX
            MFNpckNjVkQvUk90TlJQeCtVSlVtdkFBWWx3CnF6VVd3QkhXQ2JxK0RMUyt3NGwv
            QnA3dDVST3JlSGYrbEYyUStLVjJ6TmsKLS0tIFhPTUJGOXdiYTB3YVFnYk9QUmM3
            dWdncVNFNkUzUnhGWlVKUG82WHNwRjQK/xOzIiSgOykaTfZ/j6Gsx3xtrQEJloPZ
            NpO+SRIjEgjCLOwyh2mzaUnEshNn1NsJ3yqrbqYGnQChiiDBxiCzHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xdlmmj7gvvmvpl7n28yv6l9zsrrlazyunesyrzhzy37n59zexepsp4gpxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcjZXMEtQeW1ieEljajU1
            aklkMHRDcWlKZE5ZTHNaSWFzOGlHdDZmb2xRCkJWL09BaDJDSVJvd0x1WHFWUHEx
            NzBGbU83YTFqZ1hZWEx3ZmZWeHpIVXcKLS0tIFBJU0pSSndrMzBYRm1SSzVRa1Vn
            Smd3WFlzdU1DYy9aeVdGaHZoMkpUMVEK4BsDBJcb9Prw2j96zThg6o3/ROO1lA//
            N8jgDS4AY2zwJMQlUXv3D2+h6Vs0FAGk//9bjzi88DTBl6v7r51gXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tq709kc2hfq7l6g36gc95lzrl0qlhr90rpu8gyllu2k6mmldcvtq6x7xmq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MDB1TTVQcXUzZlNvNGh0
            M2l2b2wyby9YcDd6Vm1FM0NiaG1heGhmelhFCi9xbXU2cmpRVEN5eGh0ZEhNN1hB
            cVBEYXlJYU9hYm1iT0IreGZ1Z2FZQ2cKLS0tIDF5ZXFyZStFYUJoTnpLSEt3Y2F3
            b0ttSW9nV3lLK29pZXNTU1FxdkVGZEUKwpFgwAZE3fCP9eS62lQYARnOUPzZCs8q
            ELqRf8KqttGPyznV3VcxomMJUcPD4dx7p7906nSHcgRVjk7Xz7fXUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18cwlfuth4jpz03u9wzwq5rxxxx50w9e0me9sjqt29dtra0xh33ss7xtfs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWFBKck1nc2RGZm9lSHhm
            NC9oT1laZVk3RkpZeVltekp2T3Z1OExPL0RFCjl1VWJHQi9kZnNrS2plTUh6OFRP
            M3BSMERHVHViUjdLSkxyOUdUYVBVcTQKLS0tIFRmNE5zcURac1Fkc2Rod1BQMVZm
            SkdjMC9waU9LeWtvV3E3anpzeEtGd1UKffKHi4b11qNaqcEvorKzSt7SKIzQLuFq
            nTwm2XccXVonwwhSj2wMtav+n2FYTIj+LAdXN0yYWO4dn66UkrAU0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-19T04:37:38Z"
    mac: ENC[AES256_GCM,data:jp/HZytO127tp3BlV3vsXLym+OBqDrY5xjUKcOtiMlsBRAiUazwkqXhSs3WZxhFpvvUT/VJlr+yFGpxsMmVnD1WRbjmSoFHGLH/VAB2qFQSHrF93DoAcOaU/myY+/3yjP3CO2FDtRl+sCQ/6X2yoLYyhFuf6arxbl0yfOEDF+xE=,iv:HZm4FhXvWkqQF010Y/g/5uSQ1b7HvTsMussDEjr1y78=,tag:Hh5ub5RsV/C01H3C7vVYKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
