hello: ENC[AES256_GCM,data:gxsAjAjBK32cH+65k65lzGxdCZuqGTWgW8KTIRAVEOodU1MoYlI1ubAtE/Av,iv:alisjQNsVFpqV2x+8jEHuhPtJO7HSRaJwMkcB54DH6s=,tag:b34GrLthuEHFVJYwJKhmQg==,type:str]
example_key: ENC[AES256_GCM,data:w6HKDHfBuh9xV1r6qg==,iv:YJ5IDcPclkzMpFElRZr9xhCO9M6YsX4rBCv6ga7CwPw=,tag:u5QdShkQIB1v2KuNDbAIMA==,type:str]
#ENC[AES256_GCM,data:ZG/Y1X/qKGamYb1Ei9gK6Q==,iv:y5dh1QmU3RAfWrmArhhw2zxHZ6Smnq1ADfv8GlJM/3w=,tag:LtshHMzctyNIaWjmTRd1NA==,type:comment]
example_array:
    - ENC[AES256_GCM,data:77nhbqtrdtmutXGF2M4=,iv:ksjrGWaU0/iK8q1Eb75O0IqF74fOHcE3M0iGyzc90Sw=,tag:EuoAKK+t2RJuXBtGvVedbQ==,type:str]
    - ENC[AES256_GCM,data:eygOZcrWz7N2cOLvLhk=,iv:3wnl9Y2SKVm21D8YoC6zDrw8+bpNdmingaEurOK9xEQ=,tag:YQgzCwejUjdxgp2MOkMGRw==,type:str]
example_number: ENC[AES256_GCM,data:Nuou63fYRkMnEw==,iv:pDVj56e2cu5Lpm6/jyC9E11SjEzyNut3f0uJMYJjS20=,tag:UEtyAVxHlBcJMn/hifNWeg==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:mPNV/Q==,iv:QtmqDV8yYl71HvnouMZ/cSrjg4e3rW1YPZ3e5SoA7N4=,tag:Ruw4tZkq8vDyAbSKo6Mzcw==,type:bool]
    - ENC[AES256_GCM,data:USgDCys=,iv:xXi8werRtG3+BkPiVY3Tz2h4uQecMbYMf8uDPR1ZRXI=,tag:LjXQdj1DsBd8qMz0iiX9AQ==,type:bool]
sops:
    age:
        - recipient: age1jycrhjpfpw2n9rszq6056zqt3552pr38d3vz2mk8udetglrk0pfqhfhtnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VVZwVjlpUEJXcFVOWStv
            ZkR5RUtoMzkyd3NucU5zR0cwY0YrTWtZckRVClJYNzEzc3RwZW85SHpvam1selQ4
            WGpGNnNRWC9LblM0U1V1R3dNK1NDeDgKLS0tIGxTd0dUajY0RnVCY2NOWTlEUnE2
            UWhKSENhS3FadmFJdWJKLzF0Mko2T1kK39suqt/UlXsvD5cCSrsrYOAulgR3cnki
            at+4tTKtD5rxFzdIRpU8c2A1o7nKdnn3/T9ctWQNDzuO5N4kZmCy8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xdlmmj7gvvmvpl7n28yv6l9zsrrlazyunesyrzhzy37n59zexepsp4gpxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBanFBNklWY1NINHg3OElD
            YWkxS0pjcnhiTDVxZWJ0UXViVHh5MnZKZENvCko3VWw4M3A3aWlHd0x1Rm1lTmxk
            R1ZsRUFiQ2hXN1N3aVBKZ29mSTVzdFUKLS0tIHo2dFFSM2NCZnREM0lQRC8zT0Vm
            V1NRcHF5ZnozczFNMWEyUlJhY2RUQVEKepIcaGfLhC3gx9+oqjp8XR6Nm8168xcv
            uu4H2dQ6V0yKUSnTHSznnDMbOTODDGMDKXn23YRRPceSATh/fb3n2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l87qwdwrfne2mrln99qnek0yl72xecg5lrgkqps9cpz7z356kf2s4hsplc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybU9pZ3FpWFBWT0tjemdr
            L1FTbzZIWC80ZTduU2ZGcEFhdlZ1N2wrbXpZCmFTY2hCWElJelo0ZFRLWldIMjhE
            WWpOZGpWUWROUGJSNkYzT2pXUVplSW8KLS0tIGttN2llc1ZKbWQ3Ti81anZiNWpy
            dldsTmR2SFdUNUVSaVlqYncxK0tjZU0Kw7WzB406h7eD9nCCG2+n5/QDtIMiuM9L
            1W9QMPRRNN+OxPL7rfLq0+e43tXh4Md6wyUFsIM498YVrd54URDHkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18cwlfuth4jpz03u9wzwq5rxxxx50w9e0me9sjqt29dtra0xh33ss7xtfs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabDdWOW5HZWhESGxLMUhv
            dTVMZW5xeG5nelFtMG84RlllRVQ5dmdaRVhFCmlKbjM5RTVuWW9IZ1NpdXZrRDM0
            T29LVnJqZHNoRXIzVEc0a2k2NU1PYkEKLS0tIDYvbmhGaW10TDdnbmtSSXBUS09K
            WE1qcFZoeEFRc1k3L3I2MGZHbXhxQ28KRJeTQaaK2sYyMCS2DAbvfzOhpMijyU9k
            n5LJc+cs/VC66XC8N0eTJxuBa9vo/O2DJWmu1xsftwzpJuqSO45t6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T23:20:40Z"
    mac: ENC[AES256_GCM,data:E7E+hQnN5eeKOs4faElgkeMukSbyJTwDYcf3+xDLh2WC9adq6oCaj7I5siydEZ0JzIZvdMN3ygxTUqt3Cg4vYDN5XHuxHWagcEjZ9+U+W6JhutUmPcSxGWVGjtPDTWCD+xJazNuT40yvLEOK2XxA+zwPIaN/2pjARbrFa0k+Olk=,iv:CdhbcJsdPGF8UH3qOTEnkXl8l8mkl6yMqyIoYrVYoUc=,tag:WwtyCzstqBUGJaeYuc3+MA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
